.PHONY: all unit integration coverage clean

all:
	ruby run_all.rb all

unit:
	ruby run_all.rb unit

integration:
	ruby run_all.rb integration

coverage:
	ruby run_all.rb coverage

clean:
	ruby run_all.rb clean
