/*
 * gsm_process.h
 *
 *  Created on: 2 Nis 2018
 *      Author: fozcan
 */

#ifndef _GSM_PROCESS_H_
#define _GSM_PROCESS_H_

#include <gsm_types.h>
#include "gsm_dialer_process.h"


typedef enum {
	GSM_LS_IDLE,
	GSM_LS_CHECK_SOCKET_INFO,
	GSM_LS_DATA_MODE,
	GSM_LS_SEND_DATA,
	GSM_LS_CHECK_SOCKET,
	GSM_LS_CLOSE_SOCKET,
	GSM_LS_OPEN_SOCKET,
	GSM_LS_READ_SOCKET_DATA,
	GSM_LS_ACCEPT_CONNECTION,

	GSM_LS_CHECK_NET,

}ls_states_t;


typedef enum
{
	GSM_COMMON_INIT_MODE,
	GSM_MODULE_INIT_MODE,
	GSM_SIM_ERROR_MODE,
	GSM_NORMAL_MODE,
	GSM_POWER_OUTAGE_MODE,
	GSM_POWER_SAVING_MODE
}gsm_states_t;

typedef enum
{
	GSM_SOFT_INIT,
	GSM_RESET_MODULE,
	GSM_PIN_RESET,
	GSM_FACTORY_RESET,
	GSM_CHECHK_MODULE,
	GSM_GET_IMEI,
	GSM_DISABLE_FLOW_CNTRL,
	GSM_SET_BAUDRATE,
	GSM_SET_LOW_BAUDRATE,
	GSM_DISABLE_ECHO,
	GSM_ENABLE_ERROR_CODES,
	GSM_CONFIG_SIMIN_PIN,
	GSM_CONFIG_SIM_DETECTION_MODE,
	GSM_ENABLE_STAT_LED,
	GSM_GET_MODULE_NAME,
	GSM_GET_MODULE_FW_VER,
	GSM_CHECK_SIMCARD_AND_PIN,
	GSM_SET_PIN_NO,
	GSM_GET_SIMCARD_IMSI,

	GSM_GET_SUBSCRIBER_NUMBER,
	GSM_SET_SERVICE_CLASS,
	GSM_SET_GPRS_CLASS,
	GSM_CONFIG_GSM_NEWTWORK_STATE_RES,
	GSM_CHECK_GSM_VOICE_SMS_NEWTWORK_STATE,
	GSM_GET_NETWORK_INFO,
	GSM_GET_PHONE_NUMBER,
	GSM_SET_APN,
	GSM_CONFIG_GPRS_1,
	GSM_CONFIG_GPRS_2,

	GSM_CONFIG_SOCKET_WEB_SCFG,
	GSM_CONFIG_SOCKET_WEB_SCFGEXT,
	GSM_CONFIG_SOCKET_WEB_SCFGEXT2,
	GSM_CONFIG_SOCKET_WEB_SCFGEXT3,

	GSM_CONFIG_SOCKET_IEC104_SCFG,
	GSM_CONFIG_SOCKET_IEC104_SCFGEXT,
	GSM_CONFIG_SOCKET_IEC104_SCFGEXT2,
	GSM_CONFIG_SOCKET_IEC104_SCFGEXT3,



	GSM_CONFIG_TCP_WINDOW_SIZE,

	GSM_ACTIVATE_GPRS,
	GSM_CONNECT_TO_GPRS,
	GSM_GET_NTP_DATE_TIME,
	GSM_CLOSE_LISTENER_SOCKET,
	GSM_OPEN_WEB_LISTENER_SOCKET, //26
	GSM_OPEN_IEC104_LISTENER_SOCKET,
	GSM_CONFIG_FIREWALL,
	GSM_CHECK_GPRS_NEWTWORK_STATE,
	GSM_CHECK_LTE_NEWTWORK_STATE,
	GSM_CHECK_GPRS_CONNECTION,
	GSM_RECONNECT_GPRS_CONNECTION,
    GSM_SOCKET_CLOSED,
	GSM_CHECHK_LISTENER_SOCKET,
	GSM_CONFIG_PING_SUPPORT,
	GSM_CONFIG_SMS_FORMAT,
	GSM_GET_COPS_STATE,
	GSM_SET_NETWORK_TECHNOLOGY,


	GSM_ENABLE_TELIT_LOG_1,
	GSM_ENABLE_TELIT_LOG_2,

	GSM_INIT_DONE,

	GSM_GET_LISTENER_SOCKET_INFO,

	GSM_ACCEPT_CLIENT_CONNECTION,
	GSM_GET_CLIENT_SOCKET_DATA,
	GSM_GET_HEADEND_SOCKET_DATA,
	GSM_GET_SIGNAL_QUALITY,
	GSM_GET_EXT_SIGNAL_QUALITY,
	GSM_CHECK_SMS,
	GSM_DELETE_SMS,

	GSM_SHDN,
	GSM_SYSHLAT,

	GSM_GET_RES_FIRST_REBOOT,
	GSM_GET_RES_GET_MODULE_NAME,
	GSM_GET_RES_SET_BAUDRATE,
	GSM_GET_RES_DISABLE_ECHO,
	GSM_GET_RES_CHECHK_MODULE,
	GSM_GET_RES_GET_IMEI,
	GSM_GET_RES_FACTORY_RESET,
	GSM_GET_RES_DISABLE_FLOW_CNTRL,
	GSM_GET_RES_ENABLE_ERROR_CODES,
	GSM_GET_RES_CONFIG_SIMIN_PIN,
	GSM_GET_RES_CONFIG_SIM_DETECTION_MODE,
	GSM_GET_RES_ENABLE_STAT_LED,
	GSM_GET_RES_MODULE_FW_VER,
	GSM_GET_RES_CHECK_SIMCARD_AND_PIN,
	GSM_GET_RES_SET_PIN_NO,

	GSM_GET_RES_GET_SUBSCRIBER_NUMBER,
	GSM_GET_RES_SET_SERVICE_CLASS,
	GSM_GET_RES_SET_GPRS_CLASS,
	GSM_GET_RES_CONFIG_GSM_GET_RES_NEWTWORK_STATE_RES,
	GSM_GET_RES_CHECK_GSM_GET_RES_VOICE_SMS_NEWTWORK_STATE,
	GSM_GET_RES_GET_PHONE_NUMBER,
	GSM_GET_RES_APN,


	GSM_GET_RES_CONFIG_SOCKET_WEB_SCFG,
	GSM_GET_RES_CONFIG_SOCKET_WEB_SCFGEXT,
	GSM_GET_RES_CONFIG_SOCKET_WEB_SCFGEXT2,
	GSM_GET_RES_CONFIG_SOCKET_WEB_SCFGEXT3,

	GSM_GET_RES_CONFIG_SOCKET_IEC104_SCFG,
	GSM_GET_RES_CONFIG_SOCKET_IEC104_SCFGEXT,
	GSM_GET_RES_CONFIG_SOCKET_IEC104_SCFGEXT2,
	GSM_GET_RES_CONFIG_SOCKET_IEC104_SCFGEXT3,




	GSM_GET_RES_CONFIG_TCP_WINDOW_SIZE,

	GSM_GET_RES_ACTIVATE_GPRS,
	GSM_GET_RES_CONNECT_TO_GPRS,
	GSM_GET_RES_GET_NTP_DATE_TIME,
	GSM_GET_RES_CLOSE_LISTENER_SOCKET,
	GSM_GET_RES_OPEN_LISTENER_SOCKET, //26
	GSM_GET_RES_OPEN_IEC104_LISTENER_SOCKET,
	GSM_GET_RES_CONFIG_FIREWALL,
	GSM_GET_RES_CHECK_GPRS_NEWTWORK_STATE,
	GSM_GET_RES_CHECK_LTE_NEWTWORK_STATE,
	GSM_GET_RES_NETWORK_INFO,
	GSM_GET_RES_CHECK_GPRS_CONNECTION,
	GSM_GET_RES_RECONNECT_GPRS_CONNECTION,
    GSM_GET_RES_SOCKET_CLOSED,
	GSM_GET_RES_CHECHK_LISTENER_SOCKET,

	GSM_GET_RES_LISTENER_SOCKET_INFO,

	GSM_GET_RES_ACCEPT_CLIENT_CONNECTION,
	GSM_GET_RES_GET_CLIENT_SOCKET_DATA,
	GSM_GET_RES_GET_HEADEND_SOCKET_DATA,

	GSM_GET_RES_SIGNAL_QUALITY,
	GSM_GET_RES_EXT_SIGNAL_QUALITY,
	GSM_GET_RES_SYSHALT,
	GSM_GET_RES_PING_SUPPORT,
	GSM_GET_RES_CONFIG_SMS_FORMAT,
	GSM_GET_RES_SHDN,
	GSM_GET_RES_CHECK_SMS,
	GSM_GET_RES_DELETE_SMS,
	GSM_GET_RES_GET_COPS_STATE,
	GSM_GET_RES_SET_NETWORK_TECHNOLOGY,
	GSM_GET_RES_GET_SIMCARD_IMSI,

	GSM_CHECK_ALL_SOCKET_INFO,
	GSM_GET_RES_ALL_SOCKET_INFO,

	GSM_GET_RES_ENABLE_TELIT_LOG_1,
	GSM_GET_RES_ENABLE_TELIT_LOG_2,

	GSM_WAIT_FOR_EVENT,
	GSM_SEND_EVENT,

	GSM_SEARCH_NETWORK,
	GSM_GET_RES_SEARCH_NETWORK,

	GSM_DEREGISTER_NETWORK,
	GSM_GET_RES_DEREGISTER_NETWORK,

	GSM_AUTOREGISTER_NETWORK,
	GSM_GET_RES_AUTOREGISTER_NETWORK,

	GSM_MANUEL_NETWORK_REGISTER,
	GSM_GET_RES_MANUEL_NETWORK_REGISTER,

	GSM_CELL_MON,
	GSM_GET_RES_CELL_MON,

	GSM_REBOOT,
	GSM_GET_RES_REBOOT,

	GSM_GET_RFSTS,
	GSM_GET_RES_GET_RFSTS,

	GSM_GET_CEERNET,
	GSM_GET_RES_GET_CEERNET,

	GSM_GET_CEER,
	GSM_GET_RES_GET_CEER,

	GSM_SET_GPRS_Event_Reporting,
	GSM_GET_RES_GPRS_Event_Reporting,

	GSM_GET_GPRS_STATE,
	GSM_GET_RES_GET_GPRS_STATE,

	GSM_SET_SEARCHLIM,
	GSM_GET_RES_SEARCHLIM,

	GSM_SET_FPLMN,
	GSM_GET_RES_FPLMN,

	GSM_SET_DATETIME_UPDATE,
	GSM_GET_RES_DATETIME_UPDATE,

	GSM_READ_DATETIME,
	GSM_GET_RES_READ_DATETIME,

	GSM_GET_SIMCARD_CCID,
	GSM_GET_RES_SIMCARD_CCID,


	GSM_WAITFOR_INTERNET_CONNECTION,
	GSM_GET_RES_WAITFOR_INTERNET_CONNECTION,


	GSM_NO_SUB_JOB
}gsm_init_state_t;

void gsm_internet_connection_on_cb(void);

void gsm_URC_callback					(uint8_t *msg, uint16_t len);

void gsm_webserver_listener_reset_gprs_check_timer(void);
void gsm_internet_connection_faild_cd	(void);
uint32_t  gsm_http_start_file_downloader		(void);
uint32_t	 gsm_get_internet_conn_state		(void);
void gsm_clear_tx_error 				(void);
uint32_t  gsm_get_tx_error					(void);
void gsm_process_init_old   			(void);
void gsm_process_old     				(void);
uint32_t  gsm_is_ready	    				(void);



#endif /* GSM_PROCESS_H_ */
