"""Convert BOLATeX R1 captures to reproducible Ceedling fixtures.

Expected bytes come from the delivered CSVs, never from production codecs.
Run with --check to detect a stale generated header without writing files.
"""

import argparse
import binascii
import csv
import hashlib
from pathlib import Path


TEST_ROOT = Path(__file__).resolve().parents[1]
CAPTURE_ROOT = (
    TEST_ROOT.parent / "doc" / "BOLATeX_Teslim4_R1_RTU_Arayuzu_MD"
    / "Ornek_SCP_Akislari"
)
OUTPUT = TEST_ROOT / "fixtures" / "rf_scp_vectors.h"
TYPE_CODES = {"GET": 1, "SET": 2, "ACK": 3, "ERROR": 4, "PING": 5}


def byte_lines(data):
    values = [f"0x{byte:02X}U" for byte in data]
    return "\n".join(
        "    " + ", ".join(values[start:start + 8]) + ","
        for start in range(0, len(values), 8)
    )


def validate_row(row):
    logical = bytes.fromhex(row["mantiksal_hex"])
    wire = bytes.fromhex(row["hat_hex"])
    data = bytes.fromhex(row["veri_hex"])
    length = int(row["len"])
    if not 0 <= length <= 244 or len(logical) != length + 9:
        raise ValueError("Invalid logical length")
    if logical[2:7] != bytes([
        TYPE_CODES[row["tip"]], int(row["cmd"], 16),
        int(row["seq"]), length, length ^ 255,
    ]):
        raise ValueError("CSV fields disagree with logical header")
    expected_address = b"\x02\x01" if row["yon"] == "MH→RTU" else b"\x01\x02"
    if row["yon"] not in ("MH→RTU", "RTU→MH"):
        raise ValueError("Unknown direction")
    if logical[:2] != expected_address or logical[7:-2] != data:
        raise ValueError("CSV direction/payload disagrees with logical bytes")
    crc = binascii.crc_hqx(logical[:-2], 0xFFFF)
    if logical[-2:] != crc.to_bytes(2, "little"):
        raise ValueError("Invalid frame CRC")
    if not 3 <= len(wire) <= 256 or wire[0] != 0 or wire[-1] != 0:
        raise ValueError("Invalid wire envelope")
    if 0 in wire[1:-1]:
        raise ValueError("Embedded wire delimiter")
    if logical[2] == 3 and logical[3] in (0x42, 0x44):
        if not length or length % 60 or length > 240:
            raise ValueError("Invalid event batch length")
        for start in range(0, length, 60):
            record = data[start:start + 60]
            crc = binascii.crc_hqx(record[:58], 0xFFFF)
            if record[58:] != crc.to_bytes(2, "little"):
                raise ValueError("Invalid event record CRC")
    return logical, wire


def generate():
    parts = ["""/*
 * rf_scp_vectors.h
 *
 *  Created on: Oct 5, 2026
 *      Author: Fatih Ozcan
 *              fatihozcan@gmail.com
 *
 * Captured R1 bytes; generated by generate_rf_scp_vectors.py.
 * BOLATeX data: project use only; do not share with third parties.
 */

#ifndef RF_SCP_VECTORS_H
#define RF_SCP_VECTORS_H

#include <stddef.h>
#include <stdint.h>

typedef struct
{
    const char *source;
    uint16_t row;
    const uint8_t *logical;
    size_t logical_len;
    const uint8_t *wire;
    size_t wire_len;
} rf_scp_vector_t;

"""]
    entries = []
    files = sorted(CAPTURE_ROOT.glob("AY_*.csv"))
    files += sorted(CAPTURE_ROOT.glob("PWRB_*.csv"))
    if len(files) != 14:
        raise ValueError(f"Expected 14 scenario captures, found {len(files)}")
    for path in files:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        parts.append(f"/* {path.name}\n * SHA-256: {digest}\n */\n")
        with path.open(encoding="utf-8-sig", newline="") as source:
            for row_number, row in enumerate(csv.DictReader(source, delimiter=";"), 2):
                try:
                    logical, wire = validate_row(row)
                except (ValueError, KeyError) as error:
                    raise ValueError(f"{path.name}:{row_number}: {error}") from error
                index = len(entries)
                for name, data in (("logical", logical), ("wire", wire)):
                    parts.append(
                        f"static const uint8_t captured_{name}_{index}[] =\n{{\n"
                        + byte_lines(data) + "\n};\n\n"
                    )
                entries.append(
                    f'    {{"{path.name}", {row_number}U,\n'
                    f"     captured_logical_{index}, sizeof(captured_logical_{index}),\n"
                    f"     captured_wire_{index}, sizeof(captured_wire_{index})}},"
                )
    parts.append("static const rf_scp_vector_t rf_scp_vectors[] =\n{\n")
    parts.append("\n".join(entries))
    parts.append("\n};\n\n#endif /* RF_SCP_VECTORS_H */\n")
    parts.append("\n/*** end of file ***/\n")
    return "".join(parts), len(entries)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated, count = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="ascii") != generated:
            parser.exit(1, "R1 fixtures are stale; regenerate them.\n")
        print(f"R1 fixtures match all {count} frames from 14 captures.")
    else:
        OUTPUT.write_text(generated, encoding="ascii", newline="\n")
        print(f"Generated {count} captured R1 frame vectors.")


if __name__ == "__main__":
    main()
