#!/usr/bin/env python3
"""
Pre-Build Script: Generate version_gen.h with the git commit hash.
Usage: python pre-build.py [output_header]

The output file is not tracked by git. It is created if missing and only
rewritten when the hash changes, so unchanged builds do not recompile.

Hash format: 7 char short hash + "-d" (uncommitted changes) or "--" (clean).
"""

import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
DEFAULT_OUTPUT = SCRIPT_DIR.parent / "Application" / "version_gen.h"


def get_git_root():
    try:
        result = subprocess.run(
            ['git', 'rev-parse', '--show-toplevel'],
            capture_output=True, text=True, check=True, cwd=SCRIPT_DIR
        )
        return Path(result.stdout.strip())
    except Exception:
        return SCRIPT_DIR


def get_git_hash_with_status():
    try:
        git_root = get_git_root()
        git_hash = subprocess.run(
            ['git', 'rev-parse', '--short=7', 'HEAD'],
            capture_output=True, text=True, check=True, cwd=git_root
        ).stdout.strip()
        status = subprocess.run(
            ['git', 'status', '--porcelain'],
            capture_output=True, text=True, check=True, cwd=git_root
        ).stdout.strip()
        return f"{git_hash}-d" if status else f"{git_hash}--"
    except Exception as e:
        print(f"Warning: Could not get git status: {e}")
        return "unknown--"


def generate(output_path):
    git_hash = get_git_hash_with_status()
    content = (
        "/* Auto-generated by tools/pre-build.py. Do not edit or commit. */\n"
        "#ifndef _VERSION_GEN_H_\n"
        "#define _VERSION_GEN_H_\n"
        "\n"
        f'#define GIT_COMMIT_HASH\t\t("{git_hash}")\n'
        "\n"
        "#endif /* _VERSION_GEN_H_ */\n"
    )

    if output_path.exists() and output_path.read_text(encoding='utf-8') == content:
        print(f"GIT_COMMIT_HASH unchanged: {git_hash}")
        return True

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding='utf-8', newline='\n')
    print(f"GIT_COMMIT_HASH: {git_hash} -> {output_path}")
    return True


if __name__ == "__main__":
    output = DEFAULT_OUTPUT
    if len(sys.argv) > 1:
        output = Path(sys.argv[1])
        if not output.is_absolute():
            output = (SCRIPT_DIR / output).resolve()

    sys.exit(0 if generate(output) else 1)
