/**
 * @file aes_product_key.h
 * @brief Auto-generated AES-128 product key for firmware decryption.
 *
 * The key is stored XOR-masked to prevent casual extraction from
 * the binary.  Runtime deobfuscation: key[i] = masked[i] ^ mask[i].
 *
 * Generated by generate_keys.py.
 * DO NOT EDIT MANUALLY.
 */

#ifndef AES_PRODUCT_KEY_H
#define AES_PRODUCT_KEY_H

#include <stdint.h>

/* XOR-masked AES-128 key (16 bytes) */
static const uint8_t s_aes_key_masked[16] =
{
    0xEE, 0xDF, 0x88, 0x76, 0x04, 0xB7, 0xD4, 0x28,
    0x32, 0xB0, 0x6D, 0xEE, 0x7E, 0xE6, 0xF9, 0x84,
};

/* XOR mask (16 bytes) */
static const uint8_t s_aes_key_mask[16] =
{
    0x82, 0x1E, 0x75, 0x38, 0xE8, 0x64, 0x54, 0xF9,
    0xEE, 0xA5, 0xD1, 0xD1, 0x1C, 0x59, 0xAF, 0x56,
};

#endif /* AES_PRODUCT_KEY_H */
